
include(../CMakeWithClasses.cmake)


DEFINE_CLASS("CLASS_A")
DEFINE_METHOD("CLASS_A" "FOO" ARGNAME1 ARG2)
MACRO("${METHOD_NAME}")
  METHOD_RETURN(METHOD_ARGV)
ENDMACRO()

CREATE_INSTANCE("AC" "CLASS_A")

AC_FOO(1337 1338)

IF(NOT "${METHOD_ARGV}" STREQUAL "1337;1338")
  MESSAGE(SEND_ERROR "Argument passed to method incorrectly. Expected 1337;1338, got ${METHOD_ARGV}")
ENDIF()
